---
- name: "bug"
  color: ee0701
  description: "Inconsistencies or issues which cause problems for users or implementors."

- name: "feature"
  color: 0e8a16
  description: "Implementation of new functionality or capabilities."

- name: "technical-debt"
  color: fbca04
  description: "Code or architectural workarounds that should be improved or refactored later."

- name: "contribution"
  color: c2e0c6
  description: "Community-contributed issues, PRs, or ideas up for discussion or review."

- name: "documentation"
  color: 0052cc
  description: "Issues or improvements solely related to the project's documentation."
