name: Technical Debt issue
description: Create a Technical debt issue.
title: "🛠️ "
labels: ["technical-debt"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
