name: Definition of Ready for issues
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  check-definition-of-ready:
    runs-on: ubuntu-latest
    steps:
      - name: Display DoR
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: |
            ### Definition of Ready ✅
            - [ ] Story has clear business value and is understood by all team members
            - [ ] All requirements are known and documented, as well as all decisions taken during refinement/planning
            - [ ] Discussion with the stakeholders has taken place and all questions clarified
            - [ ] The story provides the smallest vertical slice of value possible (not split by technical layers)
            - [ ] Acceptance criteria are defined
            - [ ] A way to demo the story is defined
            - [ ] Story is estimated
            - [ ] Story is small enough to be completed within a single sprint
            - [ ] Ecosystem dependencies are identified and any possible blockers are addressed
            - [ ] Test case scenarios or video recordings are provided (if it's a bug)