name: Definition of Ready for issues
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  check-definition-of-ready:
    runs-on: ubuntu-latest
    steps:
      - name: Display DoR
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: |
            ### Definition of Ready ✅
            - [ ] Story has clear business value - smallest vertical slice of value possible (not split by technical layers)
            - [ ] Story is understood by everyone and all requirements and decisions (taken during refinement/planning) are known and documented
            - [ ] Criteria of acceptance (CoA) are defined
            - [ ] A way to demo the story is defined
            - [ ] Story is estimated and is small enough to be completed within a single sprint