on:
  issues:
    types:
      - opened

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: First interaction
        id: first-interaction
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            # Message with markdown.
            Welcome to the gh-actions-example repository! :wave:
