## This workflow shows how to access workflow context.
##
## More details on https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs

name: Context testing
on: workflow_dispatch

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
        # steps must have an id to be included in the context
      - id: step_generate_random_number
        name: Generate a random number
        run: |
          number=$((RANDOM))
          echo "number=$number" >> "$GITHUB_OUTPUT"
      - name: Only say Hello World, if in develop"
        if: github.ref == 'refs/heads/develop'
        run: echo "Hello World"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
